# Generated by Django 3.0.8 on 2020-07-13 20:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('blurb', models.CharField(default='', max_length=254)),
                ('story', models.TextField()),
                ('video', models.URLField()),
                ('portrait', models.ImageField(upload_to='portraits')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
