# Generated by Django 3.0.8 on 2020-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pattern1',
            field=models.ImageField(blank=True, default='', upload_to='patterns'),
        ),
        migrations.AddField(
            model_name='person',
            name='pattern2',
            field=models.ImageField(blank=True, default='', upload_to='patterns'),
        ),
        migrations.AddField(
            model_name='person',
            name='pattern3',
            field=models.ImageField(blank=True, default='', upload_to='patterns'),
        ),
    ]
