# Generated by Django 3.0.8 on 2020-07-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20200731_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pattern1',
            field=models.ImageField(blank=True, default='', upload_to='patterns'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pattern1_bg',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='pattern2',
            field=models.ImageField(blank=True, default='', upload_to='patterns'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pattern2_bg',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='pattern3',
            field=models.ImageField(blank=True, default='', upload_to='patterns'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pattern3_bg',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
