# Generated by Django 3.0.8 on 2020-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200731_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pattern1_txt',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='pattern2_txt',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='pattern3_txt',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
