# Generated by Django 3.0.8 on 2020-09-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200731_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pattern2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pattern2_bg',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pattern2_txt',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pattern3',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pattern3_bg',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pattern3_txt',
        ),
        migrations.AddField(
            model_name='person',
            name='thumb',
            field=models.ImageField(default=1, upload_to='portraits/thumbs'),
            preserve_default=False,
        ),
    ]
