# Generated by Django 3.0.8 on 2020-09-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20200926_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='portraits/thumbs'),
        ),
    ]
