# Generated by Django 3.0.8 on 2020-09-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200926_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pattern1',
            field=models.ImageField(default='', upload_to='patterns'),
        ),
    ]
