# Generated by Django 3.0.8 on 2020-09-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20200926_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pattern1_bg',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='person',
            name='pattern1_txt',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
    ]
