# Generated by Django 3.0.8 on 2020-09-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20200926_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='open_graph',
            field=models.ImageField(blank=True, upload_to='portraits/open_graph'),
        ),
    ]
